<?php

require_once 'Glossary.php';

function createMidTermGlossaryLists() {
    return [
        '11课' => [
            new Glossary('Roommate', '同屋'),
            new Glossary('Company, corporation', '公司'),
            new Glossary('Work', '工作'),
            new Glossary('Go to work, be on duty', '上班'),
            new Glossary('Weekend', '周末'),
            new Glossary('Ordinary times, normal times', '平时'),
            new Glossary('School, educational institution', '学校'),
            new Glossary('Chat', '聊天儿'),
            new Glossary('Like, love, be fond of', '喜欢'),
            new Glossary('General, ordinary, usual', '一般'),
            new Glossary('Thing, stuff', '东西'),
            new Glossary('Together, in company', '一块儿'),
            new Glossary('Put in order, tidy up, clear away', '收拾'),
            new Glossary('Room', '房间'),
        ],
        '12课' => [
            new Glossary('Interest', '兴趣'),
            new Glossary('To be interested in', '感兴趣'),
            new Glossary('But, yet, however', '可是'),
            new Glossary('Same, identical', '一样'),
            new Glossary('Or', '还是'),
            new Glossary('Sports, athletics, exercise', '运动'),
            new Glossary('Body, health', '身体'),
            new Glossary('Hobby', '爱好'),
            new Glossary('Most, least, best, to the highest or lowest degree', '最'),
            new Glossary('Right, exactly', '没错儿'),
        ],
        '13课' => [
            new Glossary('Convenient', '方便'),
            new Glossary('Expensive', '贵'),
            new Glossary('Every, each', '每'),
            new Glossary('Final, last', '最后'),
            new Glossary('Again', '又'),
            new Glossary('Be satisfied, be pleased', '满意'),
            new Glossary('Already', '已经'),
            new Glossary('Not bad, pretty good', '不错'),
            new Glossary('From, away from', '离'),
            new Glossary('Far, faraway', '远'),
            new Glossary('Walk', '走路'),
            new Glossary('Be all right, will do', '行'),
            new Glossary('Not yet', '没有'),
            new Glossary('Yesterday', '昨天'),
            new Glossary('Treat sb. (to a dinner, performance, etc.), entertain guests', '请客'),
            new Glossary('Used to inquire about nature, condition, cause, etc.', '怎么'),
            new Glossary('Come', '来'),
            new Glossary('Play, have fun', '玩儿'),
        ],
        '14课' => [
            new Glossary('This year', '今年'),
            new Glossary('Especially, particularly', '特别'),
            new Glossary('See a doctor, consult a doctor', '看病'),
            new Glossary('So, such', '这么'),
            new Glossary('Fall ill, be ill, be sick', '生病'),
            new Glossary('Weather', '天气'),
            new Glossary('But, however', '但是'),
            new Glossary('Have time off, be free', '有空儿'),
        ],
        '15课' => [
            new Glossary('Have a temporary job', '打工'),
            new Glossary('Earn money, make money', '挣钱'),
            new Glossary('Tell, let know', '告诉'),
            new Glossary('Want, wish', '要'),
            new Glossary('Be acquainted width, have knowledge of', '会'),
            new Glossary('Proper suitable', '合适'),
            new Glossary('Can, may', '可以'),
            new Glossary('Each other, mutually', '互相'),
            new Glossary('Can, be able to', '能'),
            new Glossary('College, university', '大学'),
            new Glossary('Or', '或者'),
            new Glossary('Help, do a favour, give (lend) a hand', '帮忙'),
            new Glossary('To have a holiday or vacation', '放假'),
            new Glossary('To travel, to tour', '旅游'),
            new Glossary('Vacation, holliday', '假期'),
            new Glossary('Return, go back', '回'),
            new Glossary('To drive a vehicle, automobile (car)', '开车'),
            new Glossary('Keep sb. company, to accompany', '陪'),
            new Glossary('To help', '帮'),
            new Glossary('Comparatively, relatively', '比较'),
            new Glossary('Thank, be grateful', '感谢'),
        ],
    ];
}